name = "match-generator"
type = "javascript"
route = ''
zone_id = ''
account_id = 'TODO'
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2023-04-08"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
