name = "match-generator"
main = "src/index.ts"
account_id = '8a93337e5cf183625e3ce2b4ffe43284'
workers_dev = true
compatibility_date = "2023-04-08"

[env.production.vars]
DEFAULT_SONGS_AMOUNT = "10"
DEFAULT_REPEAT_ANIMES = "false"

[observability]
enabled = true
